// Html.ts

import * as lodash from "lodash";
import type {Options} from "prettier";
import * as prettier from "prettier";
import * as vscode from "vscode";
import strip from "strip-comments";

// 0. removeComments -------------------------------------------------------------------------------
export const removeComments = async (
  contentsParam: string,
  fileTabSize: number,
  fileEol: string,
) => {
  try {
    // 1. `http://` -> `httpp`
    const pattern1 = (
      /("|')(\s*)(http:\/\/)([\n\s\S]*?)("|')/gm
    );
    const pattern2 = (
      /("|')(\s*)(https:\/\/)([\n\s\S]*?)("|')/gm
    );
    const pattern3 = (
      /("|')(\s*)(@\{http:\/\/)([\n\s\S]*?)("|')/gm
    );
    const pattern4 = (
      /("|')(\s*)(@\{https:\/\/)([\n\s\S]*?)("|')/gm
    );

    const httpResult1 = (
      lodash.chain(contentsParam)
      .replace(pattern1, (_, p1, p2, p3, p4, p5) => (
        `${p1}${p2}httpp${p4}${p5}`
      ))
      .replace(pattern2, (_, p1, p2, p3, p4, p5) => (
        `${p1}${p2}httpps${p4}${p5}`
      ))
      .replace(pattern3, (_, p1, p2, p3, p4, p5) => (
        `${p1}${p2}@{httpp${p4}${p5}`
      ))
      .replace(pattern4, (_, p1, p2, p3, p4, p5) => (
        `${p1}${p2}@{httpps${p4}${p5}`
      ))
      .value()
    );

    const { minify } = await import("html-minifier-terser");
    const minifyResult = await minify(httpResult1, {
      html5: true,
      minifyCSS: false,
      minifyJS: false,
      minifyURLs: false,
      removeComments: true,
      removeAttributeQuotes: false,
      removeEmptyAttributes: true,
      removeEmptyElements: false,
      removeOptionalTags: false,
      removeRedundantAttributes: false,
      removeTagWhitespace: false,
      keepClosingSlash: true,
      includeAutoGeneratedTags: false,
      maxLineLength: 0,
      noNewlinesBeforeTagClose: false,
      trimCustomFragments: false,
      removeStyleLinkTypeAttributes: true,
      removeScriptTypeAttributes: true,
      caseSensitive: true,
      useShortDoctype: true,
      collapseBooleanAttributes:  false,
      decodeEntities: true,
      collapseWhitespace: true,
      collapseInlineTagWhitespace: true,
      preserveLineBreaks: true,
      conservativeCollapse: true,
      preventAttributesEscaping: true,
      quoteCharacter: '"',
      sortClassName: true,
      sortAttributes: true,
      continueOnParseError: true,
      processScripts: [],
      processConditionalComments: false,
    });

    const stripResult = strip(minifyResult, {
      language: "html",
      preserveNewlines: false,
      keepProtected: false,
      block: true,
      line: true,
    });

    // 2. `httpp` -> `http://`
    const pattern1Re = (
      /("|')(\s*)(httpp)([\n\s\S]*?)("|')/gm
    );
    const pattern2Re = (
      /("|')(\s*)(httpps)([\n\s\S]*?)("|')/gm
    );
    const pattern3Re = (
      /("|')(\s*)(@\{httpp)([\n\s\S]*?)("|')/gm
    );
    const pattern4Re = (
      /("|')(\s*)(@\{httpps)([\n\s\S]*?)("|')/gm
    );
    const pattern5 = (
      /(\n)(\s*)(\n)/gm
    );

    const httpResult2 = (
      lodash.chain(stripResult)
      .replace(pattern1Re, (_, p1, p2, p3, p4, p5) => (
        `${p1}${p2}http://${p4}${p5}`
      ))
      .replace(pattern2Re, (_, p1, p2, p3, p4, p5) => (
        `${p1}${p2}https://${p4}${p5}`
      ))
      .replace(pattern3Re, (_, p1, p2, p3, p4, p5) => (
        `${p1}${p2}@{http://${p4}${p5}`
      ))
      .replace(pattern4Re, (_, p1, p2, p3, p4, p5) => (
        `${p1}${p2}@{https://${p4}${p5}`
      ))
      .replace(pattern5, (_, p1, p2, p3) => (
        `${p1}`
      ))
      .value()
    );

    console.log(`_____________________\n 'removeComments' Activated!`);
    return httpResult2;
  }
  catch (err: any) {
    console.error(err.message);
    return contentsParam;
  }
};

// 1. prettierFormat -------------------------------------------------------------------------------
export const prettierFormat = async (
  contentsParam: string,
  fileName: string,
  fileTabSize: number,
  fileEol: string
) => {
  try {
    const prettierOptions: Options = {
      parser: "html",
      singleQuote: false,
      printWidth: 1000,
      tabWidth: fileTabSize,
      useTabs: true,
      quoteProps: "as-needed",
      jsxSingleQuote: false,
      trailingComma: "all",
      bracketSpacing: false,
      jsxBracketSameLine: false,
      arrowParens: "always",
      rangeStart: 0,
      rangeEnd: Infinity,
      requirePragma: false,
      insertPragma: false,
      proseWrap: "preserve",
      htmlWhitespaceSensitivity: "ignore",
      vueIndentScriptAndStyle: true,
      endOfLine: fileEol === "lf" ? "lf" : "crlf",
      embeddedLanguageFormatting: "auto",
      singleAttributePerLine: false,
      bracketSameLine: false,
      semi: true,
    };

    const rules1 = (
      /(&nbsp;)/gm
    );
    const rules2 = (
      /(\s*)(<.*>)(<)(input|label|a|b|p|span|select|div|option)/gm
    );

    const result = (
      lodash.chain(contentsParam)
      .replace(rules1, (_, p1) => (
        ""
      ))
      .replace(rules2, (_, p1, p2, p3, p4) => (
        `${p1}${p2}\n${p1}\t${p3}${p4}`
      ))
      .value()
    );

    console.log(`_____________________\n 'prettierFormat' Activated!`);
    const prettierCode = prettier.format(result, prettierOptions);

    return prettierCode;
  }
  catch (err: any) {
    const msg = err.message.toString().trim().replace(/\x1B\[[0-9;]*[mGKF]/g, "");
    const msgRegex = /([\n\s\S]*)(\s*)(https)(.*?)([(])(.*?)([)])([\n\s\S]*)/gm;
    const msgRegexReplace = `[JLINT]\n\nError Line = [ $6 ]\nError Site = $8`;
    const msgResult = msg.replace(msgRegex, msgRegexReplace);

    console.error(`_____________________\n 'prettierFormat' Error! ('${fileName}')\n${msgResult}`);
    vscode.window.showInformationMessage(msgResult, { modal: true });
    return contentsParam;
  }
};

// 2. insertSpace ----------------------------------------------------------------------------------
export const insertSpace = async (
  contentsParam: string
) => {
  try {
    const rules1 = (
      /(\s*)(\))(\s+)(;)/gm
    );
    const rules2 = (
      /(\s*)(@)(\s*)([\s\S]*?)(\s*)(\()/gm
    );
    const rules3 = (
      /(\s*?)(ception)(\{)/gm
    );

    const result = (
      lodash.chain(contentsParam)
      .replace(rules1, (_, p1, p2, p3, p4) => (
        `${p1}${p2}${p4}`
      ))
      .replace(rules2, (_, p1, p2, p3, p4, p5, p6) => (
        `${p1}${p2}${p4} ${p6}`
      ))
      .replace(rules3, (_, p1, p2, p3) => (
        `${p2} ${p3}`
      ))
      .value()
    );

    console.log(`_____________________\n 'insertSpace' Activated!`);
    return result;
  }
  catch (err: any) {
    console.error(err.message);
    return contentsParam;
  }
};

// 3. insertLine -----------------------------------------------------------------------------------
export const insertLine = async (
  contentsParam: string
) => {
  try {
    const rules1 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]head\s*.*\s*[>])(\s*?)/gm
    );
    const rules2 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]body\s*.*\s*[>])(\s*?)/gm
    );
    const rules3 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]header\s*.*\s*[>])(\s*?)/gm
    );
    const rules4 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]main\s*.*\s*[>])(\s*?)/gm
    );
    const rules5 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]footer\s*.*\s*[>])(\s*?)/gm
    );
    const rules6 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]section\s*.*\s*[>])(\s*?)/gm
    );
    const rules7 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]table\s*.*\s*[>])(\s*?)/gm
    );
    const rules8 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]form\s*.*\s*[>])(\s*?)/gm
    );
    const rules9 = (
      /^(?!\/\/--)(?:\n*)(\s*)([<]div class="row\s*.*\s*[>])(\s*?)/gm
    );

    const result = (
      lodash.chain(contentsParam)
      .replace(rules1, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .replace(rules2, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .replace(rules3, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .replace(rules4, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .replace(rules5, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .replace(rules6, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .replace(rules7, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .replace(rules8, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .replace(rules9, (_, p1, p2, p3) => {
        const spaceSize = 100 - (p1.length + `<!--`.length + `-`.length);
        const insetLine = `<!--` + '-'.repeat(spaceSize) + `-->`;
        return `\n${p1}${insetLine}\n${p1}${p2}${p3}`;
      })
      .value()
    );

    console.log(`_____________________\n 'insertLine' Activated!`);
    return result;
  }
  catch (err: any) {
    console.error(err.message);
    return contentsParam;
  }
};

// 4. lineBreak ------------------------------------------------------------------------------------
export const lineBreak = async (
  contentsParam: string
) => {
  try {
    const rules1 = (
      /(?:\n*)(\s*)(<\/body>)(\s*?)/gm
    );
    const rules2 = (
      /(.*?)(\n*)(\s*)(\/\/ -.*>)/gm
    );

    const result = (
      lodash.chain(contentsParam)
      .replace(rules1, (_, p1, p2, p3) => (
        `\n\n${p1}${p2}${p3}`
      ))
      .replace(rules2, (_, p1, p2, p3, p4) => (
        `${p1}\n\n${p3}${p4}`
      ))
      .value()
    );

    console.log(`_____________________\n 'lineBreak' Activated!`);
    return result;
  }
  catch (err: any) {
    console.error(err.message);
    return contentsParam;
  }
};

// 5. finalCheck -----------------------------------------------------------------------------------
export const finalCheck = async (
  contentsParam: string
) => {
  try {
    const rules1 = (
      /(\s*)(<!)(--.*?)(>)(\s*)(\n)(\s*)(<!)(--.*?)(>)([\s\S])/gm
    );
    const rules2 = (
      /(\s*)(<!)(--.*?)(>)(\s*)(\n)(\s*)(<!)(--.*?)(>)([\s\S])/gm
    );

    const result = (
      lodash.chain(contentsParam)
      .replace(rules1, (_, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) => (
        `${p1}${p2}${p3}${p4}${p11}`
      ))
      .replace(rules2, (_, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) => (
        `${p1}${p2}${p3}${p4}${p11}`
      ))
      .value()
    );

    console.log(`_____________________\n 'finalCheck' Activated!`);
    return result;
  }
  catch (err: any) {
    console.error(err.message);
    return contentsParam;
  }
};